//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace warframeParse.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class warEntities : DbContext
    {
        public warEntities()
            : base("name=warEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<element> element { get; set; }
        public virtual DbSet<Polarity> Polarity { get; set; }
        public virtual DbSet<warframe> warframe { get; set; }
        public virtual DbSet<warframe_polarity> warframe_polarity { get; set; }
    }
}
