//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace warframeParse.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class warframe
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public warframe()
        {
            this.warframe_polarity = new HashSet<warframe_polarity>();
        }
    
        public System.Guid id { get; set; }
        public string name { get; set; }
        public string sex { get; set; }
        public int health { get; set; }
        public int shields { get; set; }
        public int armor { get; set; }
        public int energy { get; set; }
        public double sprint_speed { get; set; }
        public System.Guid element_id { get; set; }
    
        public virtual element element { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<warframe_polarity> warframe_polarity { get; set; }
    }
}
