//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace warframeParse.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class warframe_polarity
    {
        public System.Guid warframe_id { get; set; }
        public System.Guid polarity_id { get; set; }
        public int quantity { get; set; }
    
        public virtual Polarity Polarity { get; set; }
        public virtual warframe warframe { get; set; }
    }
}
